### ISSUE TITLE
기술 스택 정의

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-frontend#1]
# Description

해당 프로젝트에 사용할 기술 스택을 정의해주세요

![category](https://t1.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/GEd/image/3miXkKpq8fUcWiE_t2BVCc7opI8.png)

러프한 [구현 목표](https://github.com/wlwlsus/allback-with-k8s)
- 로그인 페이지
   - 아이디/비밀번호 입력 
   - 현재 사용자만 구현, (공연정보나 좌석정보를 생성하는)관리자는 존재하지 않는다.
   - OAuth (소셜로그인) 구현 없음
- 티켓 리스트 페이지 
    - 북마크한 티켓 리스트
- 티켓 상세 페이지
- 티켓 예매 정보 입력 페이지
    - 좌석 선택
    - 결제 미구현 예정
- 티켓 예매 시작/또는 중간 대기열 기능
- 상단 알림 목록 페이지 (북마크한 티켓은 'x일 후 예매를 시작합니다' 등의 알림을 보낼 수 있다)

# To do
- 카테고리별 기술 스택 정리

**Comment by junha-ahn** [comment]
개발 단계에서 중요한 것 중 하나는 **백엔드 서버에 대한 의존성**을 제거하는 것일 겁니다 (최대한)

따라서 mock server에 대한 내용도 포함되었으면 좋겠습니다.
- Json-server

## 개발 단계
1. DB ERD만 존재한다 (현재상태)
2. API Docs 만 존재한다 
3. API Docs에 맞게 구현된 서버가 존재한다.

아마 1번에 장기간 머무를 것으로 예상이 됩니다. `json-server`등의 툴이 해당 문제점을 어느정도는 해결해줄 것으로 예상합니다.

**Comment by enKODING1** [comment]
| head1 | head2  |
| --- | ---|
|   test     |   test2    |
|   test     |   test2    |
|   test     |   test2    |

**Comment by enKODING1** [comment]
| Category | technique| 
| ------------- |:-------------:|
| Integrated Framework      | React  | 
| Linting       | ESlint + Prettier|  
| UI Framework  |    MUI|
|CSS Pre-processor |Sass|
|Package Manager | npm |
|Module Bundler| webpack |
|Testing Tools | Jest / json-server |

**Comment by junha-ahn** [comment]
closed
