### ISSUE TITLE
설계 요구사항 정리

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-frontend#3]
# Description

프론트엔드 프로젝트의 설계 및 구현의 단계/방법론/예시에 대해 학습 후 정리 부탁드립니다.

현재 문제점: 해당 프로젝트에서는 어떻게 "Git Issue"를 생성할지에 대한 지식 부족

To be: 해당 문서에 정리될 내용과 레퍼런스를 통해 기능 정의에 대한 부분이 좀 더 명확화하여 향후 프로젝트 진행에 도움

# To do
- 학습한 내용의 레퍼런스와 요약 부탁드립니다.
- 프로젝트 설계/개발 단계 간단하게 명시해주세요 
    1. Figma를 통한 UIUX 정의
    2. 각 페이지 Issue 생성 후 개발 단계 시작
    3. ...
- #1 에서 명시한 예시 페이지 중 일부를 바탕으로 구현 요구사항을(예시) 만들어주세요. 
    - 예시: https://github.com/f-lab-clone/ticketing-service/issues/23

**Comment by enKODING1** [comment]
# 설계 및 구현 단계
1. 요구사항 분석
2. UI/UX 디자인
3. 기술 스택 및 도구 선택
4. 프론트엔드 아키텍처 설계
5. 개발
6. 테스트 및 디버깅
7. 성능 최적화
8. 배포

# 방법론
 컴포넌트 기반 설계와 재사용성을 강조하는 방법론을 선택
 프로젝트를 작은 독립적인 컴포넌트로 분할하고, 재사용 가능한 컴포넌트로 구축합니다.

# Issue Example 1
```
# issue title
  [design] 로그인 UI 
# Description
  Figma를 사용하여 ...

  1. ID와 PW를 입력할 수 있는 input을 구성 
  2. 로그인 버튼
  3. 회원가입 버튼

```

# Issue Example 2
```
# issue title
  [feat] 로그인 기능 구현
# Description
  1. 로그인 페이지 스켈레톤 구현 (HTML, Sass, MUI, do not use javascript)
  2. 로그인 input validation 처리
  3. 로그인 버튼 기능 (axios) 구현
  4. 테스트 구현 
```
