### ISSUE TITLE
공연 리스트 페이지 디자인

### ISSUE THREAD

**Issue by enKODING1** [f-lab-clone/ticketing-frontend#5]
# Description

공연 리스트 페이지 UI 디자인
- Base site: https://festa.io/explore

# To do
- [x] Figma 사용
- [x] Header/Footer 제외
- [x] 각 아이템은 섬네일, 제목, 날짜 정보 노출
- [x] 무한 스크롤 구현 (페이지네이션 제외)

**Comment by enKODING1** [comment]
# Figma 공연 리스트 UI

[>>공연 리스트 UI 보러가기](https://www.figma.com/file/SVAED43LUHGXFFovO3P2hn/Untitled?type=design&node-id=0%3A1&mode=design&t=vDsSa3QFqGHzAME0-1)

**Comment by junha-ahn** [comment]
링크와 함께 스크린샷으로 첨부 부탁드립니다.

**Comment by enKODING1** [comment]
# 링크 & 스크린샷
[Figma ui list](https://www.figma.com/file/SVAED43LUHGXFFovO3P2hn/Untitled?type=design&node-id=0%3A1&mode=design&t=vDsSa3QFqGHzAME0-1)
<img src="https://user-images.githubusercontent.com/65354945/255400847-8a25290b-df4b-4300-b535-c2c8a2391929.png" alt="list" width="50%">

**Comment by enKODING1** [comment]
# 링크 & 스크린샷
[Figma ui list](https://www.figma.com/file/SVAED43LUHGXFFovO3P2hn/Untitled?type=design&node-id=0%3A1&mode=design&t=vDsSa3QFqGHzAME0-1)
<img src="https://user-images.githubusercontent.com/65354945/255400847-8a25290b-df4b-4300-b535-c2c8a2391929.png" alt="list" width="50%">
