### ISSUE TITLE
공연 리스트 페이지 구현

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-frontend#6]
# Description

#5 를 바탕으로 리스트 페이지 구현

# To do

- [x] 1. 로그인 페이지 스켈레톤 구현 (HTML, Sass, MUI)
- [x] 2. json-server 구축 

```bash
GET `/events`

response: { 
    status: true, 
    message: "요청 성공",
    data: [
       {id: 1, title: '미녀와 야수', thumbnail_path: 'imagepath...', showDate: 'ISO-8601-String'}
    ]
}
```

- [x] 3. 최소 기능 구현 
    -  `/events`에서 응답하는 모든 공연을 전부 화면에 배치

- [x] 4. 최소 테스트 구현

---

<details>
<summary>접기/펼치기 - 향후 기능 구현</summary>

### 무한 스크롤 (향후 구현)

```bash
GET `/events?page_num=1&page_length=10`
- page_num : 현재 페이지 번호
- page_length: 한 페이지당 아이템 개수
```
</details>

# Test Checklist

구현 완료 이후 작성

**Comment by enKODING1** [comment]
# Front에서 테스트란

## Unit Test in Frontend

How to do 

example link...

## ... Test in Frontend


How to do 

example link...

**Comment by enKODING1** [comment]
# 프론트엔드 테스트에 대해 정리

> UNIT TEST

- testing-library 를 사용합니다.
- 리액트의 단일 컴포넌트나 서비스에 사용 합니다.
- 구조가 명확한 프로젝트에서 사용하면 좋습니다.

>  INTEGRATION TEST

- testing-library를 사용합니다.
- unit 테스트를 했던 단일 컴포넌트들의 상호작용을 테스트 합니다.

> UI TEST

- testing-library를 사용합니다.
- UI 컴포넌트 동작을 독립적인 환경에서 테스트를 하기에, 재사용 가능한 컴포넌트를 만들 수 있게 됩니다.
- Figma 와 연동이 가능합니다. 
- 컴포넌트의 동작을 파악할 수 있습니다.

> e2e TEST

- Cypress를 사용합니다. 
- 완성된 웹사이트의 전체 흐름을 확인하는 테스트 입니다. 
- node 서버를 띄어 실제 웹 페이지 환경에서 정해진 동작대로 클릭 및 타이핑을 해서 테스트를 진행 합니다.
- 사용자 관점의 시나리오 기반 테스트를 할 수 있습니다.
- 사용자 관점의 테스트를 진행하기에 많은 테스트 케이스가 필요합니다.

# 기존 테스트 업데이트 

- 기존 Poster 컴포넌트 렌더링 테스트를 story book 으로 테스트 할 수 있습니다. 

#

**Comment by junha-ahn** [comment]
### Q. UI 테스트에 대해서

리액트에서 UI 테스트라고 부르는것은 Unit Test나 Integration Test와 무엇이 다른겁니까?

> testing-library를 사용합니다.
> UI 컴포넌트 동작을 독립적인 환경에서 테스트를 하기에, 재사용 가능한 컴포넌트를 만들 수 있게 됩니다.
> Figma 와 연동이 가능합니다.
> 컴포넌트의 동작을 파악할 수 있습니다.

아래와 같이 이해하면 됩니까? 
- UI가 포함되지 않은 1개의 컴포넌트 동작을 테스트 = 유닛테스트
- UI가 포함된 1개의 컴포넌트 UI 관련 동작을 테스트 = 유닛테스트 + UI 테스트
- UI가 포함된 컴포넌트 2개 이상의 상호작용을 테스트 = 통합 테스트
- UI가 포함된 컴포넌트 2개 이상의 UI 관련 동작을 테스트 = 통합 테스트 + UI 테스트

### Q. UI 테스트와 스토리 북 테스트와의 관계는?

> 기존 Poster 컴포넌트 렌더링 테스트를 story book 으로 테스트 할 수 있습니다

렌더링 테스트는 UI 테스트라고 생각되는데, 그렇다면 story book은 어떠한 기술입니까? 

### Q. UNIT TEST와 INTEGRATION TEST의 예시 부탁드립니다

예시는 무한스크롤 또는 앞으로 ticketing 에서 사용할 페이지면 좋습니다 (회원가입 등) 
아니라면 TodoApp으로 예시 부탁드립니다. 

XXXApp은 현재 A, B, C 컴포넌트로 구성되어있습니다. 각각의 역할은 다음과 같습니다.
- A: ...
- B: ...
- C: ...
- A와 B는 리액트 xxx를 통해서 유저가 클릭시 xxx 상호작용을 합니다. 

유닛 테스트는 A 컴포넌트에 한해서 테스트를 합니다.
- Given A Component When  Rendering Then ...
- Given A Component Button When  Click Then ...

통합 테스트는 상호작용을 테스트 합니다. 아래와 같습니다.
- Given .. When... Then ...

**Comment by junha-ahn** [comment]
답변 감사합니다! 궁금했던 부분이 많이 풀렸습니다 :+1: 

해당 이슈는 여기서 Close 하고 다음 이슈로 넘어가면 좋을것 같습니다. 

무한스크롤은 #16  이슈를 참고해주세요

그리고 결국 해당 프로젝트에서는 어떤 테스트를 작성해볼지 생각해주셨으면 좋겠습니다.
- 다만 무한스크롤 구현까지는 더 이상의 새로운 테스트 방법을 도입하지는 않을 것 입니다.
- ex) 무한 스크롤 구현 이후, 리스트 페이지에 대하여 "story book" 테스트 도입 (이슈화)
